{
 "title": "DataSource",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Avg Clue Creation Time (ms)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mapping_create_clue_gauge" }
   ]
  },
  {
   "title": "Clues Submitted (/m)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ClueSubmittedCount[1m]))"
    }
   ]
  },
  {
   "title": "Avg Clue Submission Time (ms)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ClueSubmissionTime{Version=\"v2\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ClueSubmittedCount[1m]))",
     "legendFormat": "Clues submitted "
    },
    {
     "expr": "ClueSubmissionTime{Version=\"v2\"}",
     "legendFormat": "Avg clue submission time"
    },
    {
     "expr": "ClueSubmissionTime{Version=\"v1\"}",
     "legendFormat": "Avg clue submission time (synchronous)"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "increase(mapping_create_clue_error_counter[1m])",
     "legendFormat": "Error Mapping Clue"
    },
    {
     "expr": "increase(datasource_file_loading_error_counter[1m])+increase(datasource_db_loading_error_counter[1m])+increase(datasource_endpoint_loading_error_counter[1m])",
     "legendFormat": "Error Saving Counter"
    },
    {
     "expr": "increase(datasource_loading_error_from_sql_counter[1m])",
     "legendFormat": "Error DB Access"
    },
    {
     "expr": "sum(increase(ClueSubmissionException[1m]))",
     "legendFormat": "Clue submission exception"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(datasource_file_loading_gauge)",
     "legendFormat": "Avg file loading time"
    },
    { "expr": "avg(datasource_parsing_gauge)", "legendFormat": "Avg file parsing time" },
    {
     "expr": "avg(datasource_loading_db_gauge)",
     "legendFormat": "Avg database access time"
    },
    {
     "expr": "avg(datasource_db_loading_gauge)",
     "legendFormat": "Avg database loading time"
    },
    {
     "expr": "avg(datasource_endpoint_loading_gauge)",
     "legendFormat": "Avg endpoint loading time"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mapping_process_clue_counter[1m])",
     "legendFormat": "Clues sent to process"
    },
    {
     "expr": "increase(mapping_process_clue_error_counter[1m])",
     "legendFormat": "Clue processing error"
    },
    {
     "expr": "increase(mapping_processed_clued[1m])",
     "legendFormat": "Clues processed"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mapping_create_clue_counter[1m])",
     "legendFormat": "Clues created"
    },
    { "expr": "avg(mapping_create_clue_gauge)", "legendFormat": "Average creation time" }
   ]
  }
 ]
}