version: '3.7'
services:
    neo4j:
        image: cluedin/neo4j:${CLUEDIN_DOCKER_TAG}
        environment:
            - NEO4J_AUTH=none
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
        ports:
            - "7474:7474"
            - "7687:7687"
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
            - "9300:9300"
    rabbitmq:
        image: rabbitmq:3.7-management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
        hostname: cluedin-dev
    redis:
        image: redis:5.0-alpine
        ports:
            - "6379:6379"
    seq:
        image: datalust/seq:5
        environment:
            ACCEPT_EULA: 'Y'
        ports:
            - "3200:80"
            - "5341:5341"
