{
 "title": "Metrics (True/False)",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "key", "query": "employee.isactive" },
   {
    "name": "organizationId",
    "label": "Organization Id",
    "query": "b22ce7c1-137d-4466-9a3e-c62238079e47"
   },
   { "name": "friendlyName", "label": "Friendly Name", "query": "Boolean" }
  ]
 },
 "panels": [
  {
   "title": "Total Values for '${friendlyName}'",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "discoverydate",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "+${key}:* AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "'${friendlyName}' is True",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "${key}",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "organizationId:${organizationId} AND ${key}=true",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "'${friendlyName}' is False",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "${key}",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "organizationId:${organizationId} AND ${key}=false",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "Values Over Time for '${friendlyName}'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "discoverydate",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "${key}:* AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  }
 ]
}