{
 "title": "DateTime Vocabulary Key",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "key", "label": "Vocabulary Key", "query": "employee.Birthday" },
   {
    "name": "organizationId",
    "label": "Organization Id",
    "query": "b22ce7c1-137d-4466-9a3e-c62238079e47"
   },
   { "name": "dataType", "label": "Data Type", "query": "Date" }
  ]
 },
 "panels": [
  {
   "title": "Minimum Value",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "typedproperties.${key}_${dataType}",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "* AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "Maximum Value",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "typedproperties.${key}_${dataType}",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "* AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "Number of Values",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "discoverydate",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "+typedproperties.${key}_${dataType}:* AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "Empty Values",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "discoverydate",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "-typedproperties.${key}_${dataType}:* AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "Values Over Time for '${key}'",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "discoverydate",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "-t﻿ypedproperties.${key}_${dataType}:Cat AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  }
 ]
}