{
 "title": "Governance Dashboard",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "organizationId",
    "label": "Organization Id",
    "query": "b22ce7c1-137d-4466-9a3e-c62238079e47"
   }
  ]
 },
 "panels": [
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Entities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "discoverydate",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "+entityType:* AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "Total Shadow Entities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "isShadowEntity",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "* AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "Business Domains",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Business Domain Distribution",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "entityType",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "* AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "Business Domain Heatmap",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 6, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "entityType",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "* AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "Data Sources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data by Source",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "providers",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "* AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Incoming Values Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "discoverydate",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "-*:Cat AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "Last Processed Date",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "lastProcessedDate",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "* AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "Discovery Date",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "discoverydate",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "* AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "Shadow Entities Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "discoverydate",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "+isShadowEntity:true AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "Properties",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Property Count Distribution",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "propertyCount",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "* AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "Record Density",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "density",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "* AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "Number of Identifiers",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "codes",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "codes", "id": "1", "type": "cardinality" }
     ],
     "query": "* AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "persistVersion",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "* AND organizationId:${organizationId}",
     "timeField": "discoverydate"
    }
   ]
  }
 ]
}