version: '3.7'
services:
    neo4j:
        image: cluedin/neo4j:${CLUEDIN_NEO4J_TAG}
        environment:
            - NEO4J_AUTH=none
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
        ports:
            - "${CLUEDIN_NEO4J_HTTP_LOCALPORT:-7474}:7474"
            - "${CLUEDIN_NEO4J_BOLT_LOCALPORT:-7687}:7687"
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
        environment:
            - discovery.type=single-node
        ports:
            - "${CLUEDIN_ELASTIC_HTTP_LOCALPORT:-9200}:9200"
            - "${CLUEDIN_ELASTIC_DATA_LOCALPORT:-9300}:9300"
    rabbitmq:
        image: rabbitmq:3.7-management-alpine
        ports:
            - "${CLUEDIN_RABBITMQ_DATA_LOCALPORT:-5672}:5672"
            - "${CLUEDIN_RABBITMQ_HTTP_LOCALPORT:-15672}:15672"
        hostname: cluedin-dev
    redis:
        image: redis:5.0-alpine
        ports:
            - "${CLUEDIN_REDIS_LOCALPORT:-6379}:6379"
    seq:
        image: datalust/seq:5
        environment:
            ACCEPT_EULA: 'Y'
        ports:
            - "${CLUEDIN_SEQ_UI_LOCALPORT:-3200}:80"
            - "${CLUEDIN_SEQ_DATA_LOCALPORT:-5341}:5341"
    openrefine:
        image: cluedin/openrefine:${CLUEDIN_OPENREFINE_TAG}
        ports:
            - "${CLUEDIN_OPENREFINE_LOCALPORT:-3333}:3333"