version: '3.7'
services:
    sqlserver:
        image: ${CLUEDIN_CONTAINER_REGISTRY:-cluedinprod.azurecr.io}/cluedin/sqlserver:${CLUEDIN_SQLSERVER_TAG}
        entrypoint: ["sh","-c","mkdir -p /mssql-data/data/ && /init/init.sh"]
        ports:
            - "${CLUEDIN_SQLSERVER_LOCALPORT:-1433}:1433"
        environment:
            - MSSQL_INIT_LOCK=/mssql-data/data
            - MSSQL_DATA_DIR=/mssql-data/data/
            - MSSQL_LOG_DIR=/mssql-translog/translog/
            - MSSQL_MASTER_DATA_FILE=/mssql-data/master/master.mdf
            - MSSQL_MASTER_LOG_FILE=/mssql-data/master/mastlog.ldf

