version: '3.7'
services:
    webapi:
        image: cluedin/app:${CLUEDIN_DOCKER_TAG}
        environment:
        - ConnectionStrings__AuthenticationStore=Data Source=${CLUEDIN_DB_HOST};Initial Catalog=DataStore.Db.Authentication;User Id=${CLUEDIN_DB_USER};Password=${CLUEDIN_DB_PASS};MultipleActiveResultSets=True;connection timeout=0;Max Pool Size=200;Pooling=True;;
        - ConnectionStrings__CluedInEntities=Data Source=${CLUEDIN_DB_HOST};Initial Catalog=DataStore.Db.OpenCommunication;User Id=${CLUEDIN_DB_USER};Password=${CLUEDIN_DB_PASS};MultipleActiveResultSets=True;connection timeout=0;Max Pool Size=200;Pooling=True;;
        - ConnectionStrings__WebAppStore=Data Source=${CLUEDIN_DB_HOST};Initial Catalog=DataStore.Db.WebApp;User Id=${CLUEDIN_DB_USER};Password=${CLUEDIN_DB_PASS};MultipleActiveResultSets=True;connection timeout=0;Max Pool Size=200;Pooling=True;;
        - ConnectionStrings__DataProtectionPersistence=redis
        - ASPNETCORE_ENVIRONMENT=${CLUEDIN_ENVIRONMENT}
        - ASPNETCORE_URLS=http://+:9008
        - Serilog__MinimumLevel__Default=Debug
        - Serilog__WriteTo__1__Name=Seq
        - Serilog__WriteTo__1__Args__serverUrl=${CLUEDIN_SEQ_URL}
        - LegacyEndpoints__Auth__BaseUri=http://cluedin:9001
        - LegacyEndpoints__Auth__Endpoints__Token=connect/token
        - EmailSettings__AppSubdomain=app
        - EmailSettings__AppUrl=http://app.127.0.0.1.xip.io
        - EmailSettings__SmtpHost=${CLUEDIN_EMAIL_HOST}
        - EmailSettings__SmtpPort=${CLUEDIN_EMAIL_PORT}
        - EmailSettings__FromAddress=${CLUEDIN_EMAIL_SENDER}
        - EmailSettings__SmtpUserName=${CLUEDIN_EMAIL_USER}
        - EmailSettings__SmtpPassword=${CLUEDIN_EMAIL_PASS}
        depends_on:
        - seq
        - redis
        - sqlserver
        - cluedin
        ports:
        - "9008:9008"
