version: '3.7'
services:
    smtp4dev:
        image: ${CLUEDIN_CONTAINER_REGISTRY:-cluedinprod.azurecr.io}/rnwood/smtp4dev:latest
        ports:
            - "${CLUEDIN_SMTP_HTTP_LOCALPORT:-25258}:80"
            - "${CLUEDIN_SMTP_EMAIL_LOCALPORT:-2525}:25"
    neo4j:
        image: ${CLUEDIN_CONTAINER_REGISTRY:-cluedinprod.azurecr.io}/cluedin/neo4j:${CLUEDIN_NEO4J_TAG}
        environment:
            - NEO4J_AUTH=none
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
        ports:
            - "${CLUEDIN_NEO4J_HTTP_LOCALPORT:-7474}:7474"
            - "${CLUEDIN_NEO4J_BOLT_LOCALPORT:-7687}:7687"

    elasticsearch:
        image: ${CLUEDIN_CONTAINER_REGISTRY:-cluedinprod.azurecr.io}/elasticsearch/elasticsearch:7.8.0
        environment:
            - discovery.type=single-node
        ports:
            - "${CLUEDIN_ELASTIC_HTTP_LOCALPORT:-9200}:9200"
            - "${CLUEDIN_ELASTIC_DATA_LOCALPORT:-9300}:9300"

    rabbitmq:
        image: ${CLUEDIN_CONTAINER_REGISTRY:-cluedinprod.azurecr.io}/bitnami/rabbitmq:3.10.8-debian-11-r4
        ports:
            - "${CLUEDIN_RABBITMQ_DATA_LOCALPORT:-5672}:5672"
            - "${CLUEDIN_RABBITMQ_HTTP_LOCALPORT:-15672}:15672"
            - "${CLUEDIN_RABBITMQ_METRICS_LOCALPORT:-15692}:15692"
        environment:
            - RABBITMQ_USERNAME=${CLUEDIN_RABBITMQ_USERNAME:-cluedin}
            - RABBITMQ_PASSWORD=${CLUEDIN_RABBITMQ_PASSWORD:-cluedin}
        hostname: cluedin-dev
        volumes:
            - type: bind
              source: ./prometheus/rabbitmq.conf
              target: /etc/rabbitmq/conf.d/rabbitmq.conf
    redis:
        image: ${CLUEDIN_CONTAINER_REGISTRY:-cluedinprod.azurecr.io}/bitnami/redis:6.2.7-debian-11-r11
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "${CLUEDIN_REDIS_LOCALPORT:-6379}:6379"
    seq:
        image: ${CLUEDIN_CONTAINER_REGISTRY:-cluedinprod.azurecr.io}/datalust/seq:2022.1
        environment:
            ACCEPT_EULA: 'Y'
        ports:
            - "${CLUEDIN_SEQ_UI_LOCALPORT:-3200}:80"
            - "${CLUEDIN_SEQ_DATA_LOCALPORT:-5341}:5341"
    openrefine:
        image: ${CLUEDIN_CONTAINER_REGISTRY:-cluedinprod.azurecr.io}/cluedin/openrefine:${CLUEDIN_OPENREFINE_TAG}
        ports:
            - "${CLUEDIN_OPENREFINE_LOCALPORT:-3333}:3333"
    prometheus:
        image: ${CLUEDIN_CONTAINER_REGISTRY:-cluedinprod.azurecr.io}/prometheus/prometheus:v2.37.0
        deploy:
            replicas: ${CLUEDIN_PROMETHEUS_SCALE_COUNT:-0}
        ports:
            - "9090:9090"
        volumes:
            - type: bind
              source: ./prometheus/prometheus.yml
              target: /etc/prometheus/prometheus.yml
        command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    grafana:
        image: ${CLUEDIN_CONTAINER_REGISTRY:-cluedinprod.azurecr.io}/grafana/grafana:9.1.4
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_SECURITY_ALLOW_EMBEDDING=true
            - GF_USERS_DEFAULT_THEME=light
            - GF_USERS_ALLOW_SIGN_UP=false
            - GF_USERS_ALLOW_ORG_CREATE=false
            - GF_AUTH_DISABLE_SIGNOUT_MENU=true
        ports:
            - "3030:3000"
        volumes:
            - type: bind
              source: ./grafana/dashboards.yml
              target: /etc/grafana/provisioning/dashboards/dashboards.yml
            - type: bind
              source: ./grafana/datasource.yml
              target: /etc/grafana/provisioning/datasources/datasource.yml
            - type: bind
              source: ./grafana/datasource-dashboard.json
              target: /var/lib/grafana/dashboards/datasource-dashboard.json
            - type: bind
              source: ./grafana/streams-dashboard.json
              target: /var/lib/grafana/dashboards/streams-dashboard.json
            - type: bind
              source: ./grafana/rabbitmq-dashboard.json
              target: /var/lib/grafana/dashboards/rabbitmq-dashboard.json
            - type: bind
              source: ./grafana/cadvisor.json
              target: /var/lib/grafana/dashboards/cadvisor.json
            - type: bind
              source: ./grafana/cadvisor-global.json
              target: /var/lib/grafana/dashboards/cadvisor-global.json
    cadvisor:
        image: ${CLUEDIN_CONTAINER_REGISTRY:-cluedinprod.azurecr.io}/cadvisor/cadvisor:latest
        ports:
            - "8484:8080"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        depends_on:
            - sqlserver
