version: '3.7'
services:
    webapi:
        image: cluedin/app:${CLUEDIN_WEBAPI_TAG}
        environment:
        - ConnectionStrings__AuthenticationStore=Data Source=${CLUEDIN_SQLSERVER_HOST};Initial Catalog=DataStore.Db.Authentication;User Id=${CLUEDIN_SQLSERVER_USER};Password=${CLUEDIN_SQLSERVER_PASS};MultipleActiveResultSets=True;connection timeout=0;Max Pool Size=200;Pooling=True;;
        - ConnectionStrings__CluedInEntities=Data Source=${CLUEDIN_SQLSERVER_HOST};Initial Catalog=DataStore.Db.OpenCommunication;User Id=${CLUEDIN_SQLSERVER_USER};Password=${CLUEDIN_SQLSERVER_PASS};MultipleActiveResultSets=True;connection timeout=0;Max Pool Size=200;Pooling=True;;
        - ConnectionStrings__WebAppStore=Data Source=${CLUEDIN_SQLSERVER_HOST};Initial Catalog=DataStore.Db.WebApp;User Id=${CLUEDIN_SQLSERVER_USER};Password=${CLUEDIN_SQLSERVER_PASS};MultipleActiveResultSets=True;connection timeout=0;Max Pool Size=200;Pooling=True;;
        - ConnectionStrings__DataProtectionPersistence=${CLUEDIN_REDIS_HOST:-redis}
        - ASPNETCORE_ENVIRONMENT=${CLUEDIN_ENVIRONMENT}
        - ASPNETCORE_URLS=http://+:9008
        - Serilog__MinimumLevel__Default=Debug
        - Serilog__WriteTo__1__Name=Seq
        - Serilog__WriteTo__1__Args__serverUrl=http://${CLUEDIN_SEQ_HOST:-seq}
        - LegacyEndpoints__Auth__BaseUri=http://${CLUEDIN_SERVER_HOST:-server}:9001
        - LegacyEndpoints__Auth__Endpoints__Token=connect/token
        - EmailSettings__AppSubdomain=app
        - EmailSettings__AppUrl=http://app.${CLUEDIN_DOMAIN}:${CLUEDIN_UI_LOCALPORT:-9080}
        - EmailSettings__SmtpHost=${CLUEDIN_EMAIL_HOST}
        - EmailSettings__SmtpPort=${CLUEDIN_EMAIL_PORT}
        - EmailSettings__FromAddress=${CLUEDIN_EMAIL_SENDER}
        - EmailSettings__SmtpUserName=${CLUEDIN_EMAIL_USER}
        - EmailSettings__SmtpPassword=${CLUEDIN_EMAIL_PASS}
        - EmailSettings__SpecifiedPickupDirectory=${CLUEDIN_EMAIL_DIR:-}
        - ASPNETCORE_WEBROOT=/
        volumes:
        - ".${CLUEDIN_EMAIL_DIR:-}:${CLUEDIN_EMAIL_DIR:-/emails}"
        depends_on:
        - seq
        - redis
        - sqlserver
        ports:
        - "${CLUEDIN_WEBAPI_LOCALPORT:-9008}:9008"
