version: '3.7'
services:
  clean:
    user: root
    image: cluedin/cluedin-micro-clean:${CLUEDIN_CLEAN_TAG}
    environment:
    - WEB_API=http://${CLUEDIN_SERVER_HOST:-server}:9000/
    - RabbitMQ_CS=amqp://${CLUEDIN_RABBITMQ_USERNAME:-guest}:${CLUEDIN_RABBITMQ_PASSWORD:-guest}@${CLUEDIN_RABBITMQ_HOST:-rabbitmq}:5672
    - ElasticURL=http://${CLUEDIN_ELASTIC_HOST:-elasticsearch}:9200
    - SeqURL=http://${CLUEDIN_SEQ_HOST:-seq}:5341
    - SeqLoggingLevel=debug
    - LegacyURL=http://${CLUEDIN_SERVER_HOST:-server}:9000
    - DbHost=${CLUEDIN_SQLSERVER_HOST}
    - DbPassword=${CLUEDIN_SQLSERVER_PASS}
    - DbUserName=${CLUEDIN_SQLSERVER_USER}
    - DbName=${CLUEDIN_CLEAN_DBNAME:-DataStore.Db.MicroServices}
    - ForceTableCreation=${CLUEDIN_CLEAN_FORCETABLECREATION:-false}
    - AnnotationURL=http://${CLUEDIN_ANNOTATION_HOST:-annotation}:${CLUEDIN_ANNOTATION_PORT:-8888}
    - DataSourceURL=http://${CLUEDIN_DATASOURCE_HOST:-datasource}:${CLUEDIN_DATASOURCE_PORT:-8888}
    - NODE_ENV=${CLUEDIN_ENVIRONMENT}
    ports:
      - "${CLUEDIN_CLEAN_LOCALPORT:-9009}:8888"
    depends_on:
    - elasticsearch
    - rabbitmq
    - sqlserver
    - seq
    - annotation
    - datasource

  annotation:
    user: root
    image: cluedin/cluedin-micro-annotation:${CLUEDIN_ANNOTATION_TAG}
    environment:
    - WEB_API=http://${CLUEDIN_SERVER_HOST:-server}:9000/
    - RabbitMQ_CS=amqp://${CLUEDIN_RABBITMQ_USERNAME:-guest}:${CLUEDIN_RABBITMQ_PASSWORD:-guest}@${CLUEDIN_RABBITMQ_HOST:-rabbitmq}:5672
    - DbHost=${CLUEDIN_SQLSERVER_HOST}
    - DbPassword=${CLUEDIN_SQLSERVER_PASS}
    - DbUserName=${CLUEDIN_SQLSERVER_USER}
    - DbName=${CLUEDIN_ANNOTATION_DBNAME:-DataStore.Db.MicroServices}
    - SeqURL=http://${CLUEDIN_SEQ_HOST:-seq}:5341
    - SeqLoggingLevel=debug
    - ForceTableCreation=${CLUEDIN_ANNOTATION_FORCETABLECREATION:-false}
    - NODE_ENV=${CLUEDIN_ENVIRONMENT}
    - MICRO_DATASOURCE_URL=http://${CLUEDIN_DATASOURCE_HOST:-datasource}:${CLUEDIN_DATASOURCE_PORT:-8888}
    ports:
      - "${CLUEDIN_ANNOTATION_LOCALPORT:-9010}:8888"
    depends_on:
    - rabbitmq
    - sqlserver
    - seq
    - datasource


  datasource:
    user: root
    image: cluedin/cluedin-micro-datasource:${CLUEDIN_DATASOURCE_TAG}
    environment:
    - RabbitMQ_CS=amqp://${CLUEDIN_RABBITMQ_USERNAME:-guest}:${CLUEDIN_RABBITMQ_PASSWORD:-guest}@${CLUEDIN_RABBITMQ_HOST:-rabbitmq}:5672
    - ElasticURL=http://${CLUEDIN_ELASTIC_HOST:-elasticsearch}:9200
    - DbName=${CLUEDIN_DATASOURCE_DBNAME:-DataStore.Db.MicroServices}
    - DbHost=${CLUEDIN_SQLSERVER_HOST}
    - DbPassword=${CLUEDIN_SQLSERVER_PASS}
    - DbUserName=${CLUEDIN_SQLSERVER_USER}
    - SeqURL=http://${CLUEDIN_SEQ_HOST:-seq}:5341
    - SeqLoggingLevel=debug
    - AnnotationURL=http://${CLUEDIN_ANNOTATION_HOST:-annotation}:${CLUEDIN_ANNOTATION_PORT:-8888}/
    - ConsoleLoggingLevel=info
    - ForceTableCreation=${CLUEDIN_DATASOURCE_FORCETABLECREATION:-false}
    - NODE_ENV=${CLUEDIN_ENVIRONMENT}
    - WEB_API=http://${CLUEDIN_SERVER_HOST:-server}:9000/
    ports:
      - "${CLUEDIN_DATASOURCE_LOCALPORT:-9011}:8888"
      - "${CLUEDIN_DATASOURCE_PROMETHEUS_ENDPOINT_METRICS_LOCALPORT:-9014}:9014"
      - "${CLUEDIN_DATASOURCE_PROMETHEUS_FILE_METRICS_LOCALPORT:-9015}:9015"
      - "${CLUEDIN_DATASOURCE_PROMETHEUS_SQL_METRICS_LOCALPORT:-9016}:9016"
    depends_on:
    - elasticsearch
    - rabbitmq
    - sqlserver
    - seq

  submitter:
    image: cluedin/cluedin-micro-submitter-node:${CLUEDIN_SUBMITTER_TAG}
    environment:
      CluedIn_API_URL: ${CLUEDIN_SUBMITTER_CLUE_API_URL:-/api/v2/clue?save=true}
      RabbitMQ_CS: "amqp://${CLUEDIN_RABBITMQ_USERNAME:-guest}:${CLUEDIN_RABBITMQ_PASSWORD:-guest}@${CLUEDIN_RABBITMQ_HOST:-rabbitmq}:5672"
      Serilog__WriteTo__1__Name: Seq
      Serilog__WriteTo__1__Args__serverUrl: http://${CLUEDIN_SEQ_HOST:-seq}:5341
      Serilog__WriteTo__1__Args__controlLevelSwitch: "$$controlSwitch"
      DbName: ${CLUEDIN_DATASOURCE_DBNAME:-DataStore.Db.MicroServices}
      DbHost: ${CLUEDIN_SQLSERVER_HOST}
      DbPassword: ${CLUEDIN_SQLSERVER_PASS}
      DbUserName: ${CLUEDIN_SQLSERVER_USER}
      MICRO_DATASOURCE_URL: http://${CLUEDIN_DATASOURCE_HOST:-datasource}:${CLUEDIN_DATASOURCE_PORT:-8888}
      APP_API_URL: http://${CLUEDIN_SERVER_HOST:-server}:9007
      WORKERS_NUMBER: 4
      DISABLE_SUBMISSION_REPORT: 'false'
    ports:
      - "${CLUEDIN_SUBMITTER_LOCALPORT:-9012}:8888"
    depends_on:
    - rabbitmq
    - seq
    - annotation
