version: '3.7'
services:
  ui:
    user: root
    image: cluedin/ui:${CLUEDIN_UI_TAG}
    ports:
    - "${CLUEDIN_UI_LOCALPORT:-9080}:8080"
    environment:
    - REACT_APP_UI_APP=http://app.${CLUEDIN_DOMAIN}:${CLUEDIN_UI_LOCALPORT:-9080}
    - REACT_APP_UI_APP_SUBDOMAIN=app
    - REACT_APP_UI_BUCKET=/public/img/providers/
    - REACT_APP_UI_CDN_URL=/
    - REACT_APP_UI_CLUEDIN_APP_DOMAIN=${CLUEDIN_DOMAIN}
    - REACT_APP_UI_CLUEDIN_FEATURES=${CLUEDIN_UI_FEATURES_ANNOTATION};${CLUEDIN_UI_FEATURES_CLEAN};${CLUEDIN_UI_FEATURES_CONNECTOR};${CLUEDIN_UI_FEATURES_DATAGOVERNANCE};${CLUEDIN_UI_FEATURES_DATASOURCE};${CLUEDIN_UI_FEATURES_DEDUPLICATIONPROJECTS};${CLUEDIN_UI_FEATURES_DEVELOPER};${CLUEDIN_UI_FEATURES_ENDPOINT};${CLUEDIN_UI_FEATURES_ENRICHER};${CLUEDIN_UI_FEATURES_EXTENDEDSAR};${CLUEDIN_UI_FEATURES_FOLLOW};${CLUEDIN_UI_FEATURES_GLOSSARY};${CLUEDIN_UI_FEATURES_INTEGRATIONS};${CLUEDIN_UI_FEATURES_METRICS};${CLUEDIN_UI_FEATURES_OPENREFINE};${CLUEDIN_UI_FEATURES_PREPARATION};${CLUEDIN_UI_FEATURES_ROLES};${CLUEDIN_UI_FEATURES_SAVEDSEARCHES};${CLUEDIN_UI_FEATURES_SETTINGS};${CLUEDIN_UI_FEATURES_STREAM_MONITORING};${CLUEDIN_UI_FEATURES_STREAMS};${CLUEDIN_UI_FEATURES_USERS}
    - REACT_APP_UI_CLUEDIN_CLEAN_URL=http://${CLUEDIN_DOMAIN}:${CLUEDIN_OPENREFINE_LOCALPORT:-3333}/
    - REACT_APP_UI_GQL_URL=http://${CLUEDIN_DOMAIN}:${CLUEDIN_GQL_LOCALPORT:-8888}/
    - REACT_APP_UI_INTERNAL_GQL_URL=${CLUEDIN_UI_ALT_UPLOAD:-http://gql:8888}
    - REACT_APP_UI_COOKIE_DOMAIN_NAME=${CLUEDIN_DOMAIN}
    - REACT_APP_UI_ENV=production
    - REACT_APP_UI_MAIN_DOMAIN=${CLUEDIN_DOMAIN}:${CLUEDIN_UI_LOCALPORT:-9080}
    - REACT_APP_UI_PROTOCOL=http://
    - REACT_APP_UI_CLUEDIN_PUBLICAPI_URL=http://${CLUEDIN_SERVER_HOST:-server}:9007
    - REACT_APP_UI_UPLOAD_LIMIT=${CLUEDIN_UI_UPLOAD_LIMIT:-1gb}
    depends_on:
    - server

  gql:
    user: root
    image: cluedin/cluedin-ui-gql:${CLUEDIN_GQL_TAG}
    environment:
        - "AUTH_API=http://${CLUEDIN_SERVER_HOST:-server}:9001/"
        - "WEB_API=http://${CLUEDIN_SERVER_HOST:-server}:9000/"
        - "MICRO_CLEAN_URL=http://${CLUEDIN_CLEAN_HOST:-clean}:${CLUEDIN_CLEAN_PORT:-8888}"
        - "MICRO_ANNOTATION_URL=http://${CLUEDIN_ANNOTATION_HOST:-annotation}:${CLUEDIN_ANNOTATION_PORT:-8888}/"
        - "MICRO_DATASOURCE_URL=http://${CLUEDIN_DATASOURCE_HOST:-datasource}:${CLUEDIN_DATASOURCE_PORT:-8888}"
        - "MICRO_SUBMITTER_URL=http://${CLUEDIN_SUBMITTER_HOST:-submitter}:${CLUEDIN_SUBMITTER_PORT:-9012}"
        - "APP_API_URL=http://${CLUEDIN_WEBAPI_HOST:-webapi}:9008/"
        - "PUBLIC_API=http://${CLUEDIN_SERVER_HOST:-server}:9007/"
        - "WEBHOOKS_URL=http://${CLUEDIN_SERVER_HOST:-server}:9006/"
        - "NODE_ENV=${CLUEDIN_ENVIRONMENT}"
        - "RabbitMQ_Notification_Channel=Notifications"
        - "RabbitMQ_CS=amqp://${CLUEDIN_RABBITMQ_USERNAME:-guest}:${CLUEDIN_RABBITMQ_PASSWORD:-guest}@${CLUEDIN_RABBITMQ_HOST:-rabbitmq}:5672"
        - "DbHost=${CLUEDIN_SQLSERVER_HOST}"
        - "DbPassword=${CLUEDIN_SQLSERVER_PASS}"
        - "DbUserName=${CLUEDIN_SQLSERVER_USER}"
        - "DbName=${CLUEDIN_GQL_DBNAME:-DataStore.Db.MicroServices}"
        - "ENGINE_ROOM_LOCAL=${CLUEDIN_GQL_ENGINE_ROOM_LOCAL:-false}"
        - "ENGINE_ROOM_STREAM_DASHBOARD_ID=h0W9h3knk"
        - "ENGINE_ROOM_STREAM_DASHBOARD_NAME=streams"
        - "UPLOAD_LIMIT=${CLUEDIN_UI_UPLOAD_LIMIT:-1gb}"
    ports:
    - "${CLUEDIN_GQL_LOCALPORT:-8888}:8888"
    depends_on:
    - annotation
    - clean
    - datasource
    - webapi
    - sqlserver