version: '3.7'
services:
  installer:
    image: cluedin/nuget-installer:${CLUEDIN_INSTALLER_TAG}
    scale: 0
  server:
    image: cluedin/cluedin-server:${CLUEDIN_SERVER_TAG}
    environment:
      - CLUEDIN_APPSETTINGS__AGENTSERVERURL=http://${CLUEDIN_DOMAIN}:9000
      - CLUEDIN_APPSETTINGS__AUTHRETURNURL=http://${CLUEDIN_DOMAIN}:9001
      - CLUEDIN_APPSETTINGS__AUTHSERVERURL=http://${CLUEDIN_DOMAIN}:9001
      - CLUEDIN_APPSETTINGS__DOMAIN=${CLUEDIN_DOMAIN}
      - CLUEDIN_APPSETTINGS__JOBSERVERDASHBOARDURL=http://*:9003
      - CLUEDIN_APPSETTINGS__NOTIFICATIONS_ADMINNOTIFICATIONS_RECIPIENT=admin@foobar.com
      - CLUEDIN_APPSETTINGS__PUBLICSERVERURL=http://*:9007
      - CLUEDIN_APPSETTINGS__SEQ_URL=http://${CLUEDIN_SEQ_HOST:-seq}
      - CLUEDIN_APPSETTINGS__SERVERBLOBURL=http://*:9000
      - CLUEDIN_APPSETTINGS__SERVERPUBLICAPIURL=http://*:9007
      - CLUEDIN_APPSETTINGS__SERVERRETURNURL=http://${CLUEDIN_DOMAIN}:9000
      - CLUEDIN_APPSETTINGS__SERVERURL=http://*:9000
      - CLUEDIN_APPSETTINGS__WEBHOOKSERVERURL=http://*:9006
      - CLUEDIN_APPSETTINGS__WEBHOOKURL=http://*:9006
      - CLUEDIN_APPSETTINGS__WEBHOOKRETURNURL=http://${CLUEDIN_DOMAIN}:9006
      - CLUEDIN_APPSETTINGS__FEATURE_CLEAN_BASEURL=http://${CLUEDIN_OPENREFINE_HOST:-openrefine}:3333/

      - CLUEDIN_CONNECTIONSTRINGS__CACHESTORE=${CLUEDIN_REDIS_HOST:-redis}:6379
      - CLUEDIN_CONNECTIONSTRINGS__DATAPROTECTIONPERSISTENCE=${CLUEDIN_REDIS_HOST:-redis}:6379
      - CLUEDIN_CONNECTIONSTRINGS__ETAGSTORE=${CLUEDIN_REDIS_HOST:-redis}:6379
      - CLUEDIN_CONNECTIONSTRINGS__JOBSTORE=${CLUEDIN_REDIS_HOST:-redis}:6379

      - CLUEDIN_CONNECTIONSTRINGS__GRAPHSTORE_READ=http://neo4j:@${CLUEDIN_NEO4J_HOST:-neo4j}:7474/db/data
      - CLUEDIN_CONNECTIONSTRINGS__GRAPHSTORE_WRITE=http://neo4j:@${CLUEDIN_NEO4J_HOST:-neo4j}:7474/db/data

      - CLUEDIN_CONNECTIONSTRINGS__MESSAGEBUS=host=${CLUEDIN_RABBITMQ_HOST:-rabbitmq};username=${CLUEDIN_RABBITMQ_USERNAME:-guest};password=${CLUEDIN_RABBITMQ_PASSWORD:-guest};product=CluedIn
      - CLUEDIN_CONNECTIONSTRINGS__SEARCHSTORE=http://${CLUEDIN_ELASTIC_HOST:-elasticsearch}:9200
      - CLUEDIN_CONNECTIONSTRINGS__SIGNALRSCALEOUT=amqp://${CLUEDIN_RABBITMQ_USERNAME:-guest}:${CLUEDIN_RABBITMQ_PASSWORD:-guest}@${CLUEDIN_RABBITMQ_HOST:-rabbitmq}:5672

      - CLUEDIN_CONNECTIONSTRINGS__AUTHENTICATIONSTORE=Data Source=${CLUEDIN_SQLSERVER_HOST};Initial Catalog=DataStore.Db.Authentication;User Id=${CLUEDIN_SQLSERVER_USER};Password=${CLUEDIN_SQLSERVER_PASS};MultipleActiveResultSets=True;connection timeout=0;Max Pool Size=200;Pooling=True
      - CLUEDIN_CONNECTIONSTRINGS__AUDITLOG=Data Source=${CLUEDIN_SQLSERVER_HOST};Initial Catalog=DataStore.Db.AuditLog;User Id=${CLUEDIN_SQLSERVER_USER};Password=${CLUEDIN_SQLSERVER_PASS};MultipleActiveResultSets=True;connection timeout=0;Max Pool Size=200;Pooling=True
      - CLUEDIN_CONNECTIONSTRINGS__BLOBSTORAGE=Data source=${CLUEDIN_SQLSERVER_HOST};Initial catalog=DataStore.Db.BlobStorage;User Id=${CLUEDIN_SQLSERVER_USER};Password=${CLUEDIN_SQLSERVER_PASS};MultipleActiveResultSets=True;connection timeout=0;Max Pool Size=200;Pooling=True
      - CLUEDIN_CONNECTIONSTRINGS__CONFIGURATIONSTORE=Data source=${CLUEDIN_SQLSERVER_HOST};Initial catalog=DataStore.Db.Configuration;User Id=${CLUEDIN_SQLSERVER_USER};Password=${CLUEDIN_SQLSERVER_PASS};MultipleActiveResultSets=True;connection timeout=0;Max Pool Size=200;Pooling=True
      - CLUEDIN_CONNECTIONSTRINGS__CLUEDINENTITIES=Data source=${CLUEDIN_SQLSERVER_HOST};Initial catalog=DataStore.Db.OpenCommunication;User Id=${CLUEDIN_SQLSERVER_USER};Password=${CLUEDIN_SQLSERVER_PASS};MultipleActiveResultSets=True;connection timeout=0;Max Pool Size=200;Pooling=True
      - CLUEDIN_CONNECTIONSTRINGS__TOKENSTORE=Data Source=${CLUEDIN_SQLSERVER_HOST};Initial Catalog=DataStore.Db.TokenStore;User Id=${CLUEDIN_SQLSERVER_USER};Password=${CLUEDIN_SQLSERVER_PASS};MultipleActiveResultSets=True;connection timeout=0;Max Pool Size=200;Pooling=True
      - CLUEDIN_CONNECTIONSTRINGS__TRAINING=Data Source=${CLUEDIN_SQLSERVER_HOST};Initial Catalog=DataStore.Db.Training;User Id=${CLUEDIN_SQLSERVER_USER};Password=${CLUEDIN_SQLSERVER_PASS};MultipleActiveResultSets=True;connection timeout=0;Max Pool Size=200;Pooling=True
      - CLUEDIN_CONNECTIONSTRINGS__EXTERNALSEARCH=Data Source=${CLUEDIN_SQLSERVER_HOST};Initial Catalog=DataStore.Db.ExternalSearch;User Id=${CLUEDIN_SQLSERVER_USER};Password=${CLUEDIN_SQLSERVER_PASS};MultipleActiveResultSets=True;connection timeout=0;Max Pool Size=200;Pooling=True
      - CLUEDIN_CONNECTIONSTRINGS__METRICS=Data Source=${CLUEDIN_SQLSERVER_HOST};Initial Catalog=DataStore.Db.Metrics;User Id=${CLUEDIN_SQLSERVER_USER};Password=${CLUEDIN_SQLSERVER_PASS};MultipleActiveResultSets=True;connection timeout=0;Max Pool Size=200;Pooling=True
      - CLUEDIN_CONNECTIONSTRINGS__ML_LOGGING=Data Source=${CLUEDIN_SQLSERVER_HOST};Initial Catalog=DataStore.Db.ML-Logging;User Id=${CLUEDIN_SQLSERVER_USER};Password=${CLUEDIN_SQLSERVER_PASS};MultipleActiveResultSets=True;connection timeout=0;Max Pool Size=200;Pooling=True
      - CLUEDIN_CONNECTIONSTRINGS__WEBAPPSTORE=Data Source=${CLUEDIN_SQLSERVER_HOST};Initial Catalog=DataStore.Db.WebApp;User Id=${CLUEDIN_SQLSERVER_USER};Password=${CLUEDIN_SQLSERVER_PASS};MultipleActiveResultSets=True;connection timeout=0;Max Pool Size=200;Pooling=True
      - CLUEDIN_APPSETTINGS__AGENT_ENABLED=${CLUEDIN_AGENT_ENABLED}
      - CLUEDIN_APPSETTINGS__MODELS_ENABLED=false
      - DOTNET_ENVIRONMENT=${CLUEDIN_ENVIRONMENT}
      - CLUEDIN_APPSETTINGS__EMAILUSERNAME=${CLUEDIN_EMAIL_USER}
      - CLUEDIN_APPSETTINGS__EMAILPASSWORD=${CLUEDIN_EMAIL_PASS}
      - CLUEDIN_APPSETTINGS__EMAILSERVER=${CLUEDIN_EMAIL_HOST}
      - CLUEDIN_APPSETTINGS__EMAILPORT=${CLUEDIN_EMAIL_PORT}
      - CLUEDIN_APPSETTINGS__EMAILSENDER=${CLUEDIN_EMAIL_SENDER}
      - CLUEDIN_APPSETTINGS__EMAILDIRECTORY=${CLUEDIN_EMAIL_DIR:-}
      - CLUEDIN_APPSETTINGS__JOBSERVER_DASHBOARDVISIBLE=${CLUEDIN_JOBS_DASHBOARD:-localOnly}
    volumes:
        - "./components:/components"
        - ".${CLUEDIN_EMAIL_DIR:-}:/app/${CLUEDIN_EMAIL_DIR:-emails}"
    ports:
      - "${CLUEDIN_SERVER_LOCALPORT:-9000}:9000"
      - "${CLUEDIN_SERVER_AUTH_LOCALPORT:-9001}:9001"
      - "${CLUEDIN_SERVER_JOB_LOCALPORT:-9003}:9003"
      - "${CLUEDIN_SERVER_WEBHOOK_LOCALPORT:-9006}:9006"
      - "${CLUEDIN_SERVER_PUBLIC_LOCALPORT:-9007}:9007"
    depends_on:
      - neo4j
      - elasticsearch
      - rabbitmq
      - redis
      - seq
      - sqlserver
