version: '3.7'
services:
    sqlserver:
        image: cluedin/sqlserver:${CLUEDIN_SQLSERVER_TAG}
        entrypoint: ["sh","-c","/init/init.sh"]
        ports:
            - "${CLUEDIN_SQLSERVER_LOCALPORT:-1433}:1433"
