version: '3.7'
services:
  ui:
    image: cluedin/ui:${CLUEDIN_DOCKER_TAG}
    ports:
    - "${CLUEDIN_UI_LOCALPORT:-80}:80"
    environment:
    - REACT_APP_UI_APP=http://app.${CLUEDIN_DOMAIN}
    - REACT_APP_UI_APP_SUBDOMAIN=app
    - REACT_APP_UI_BUCKET=/public/img/providers/
    - REACT_APP_UI_CDN_URL=/
    - REACT_APP_UI_CLUEDIN_APP_DOMAIN=${CLUEDIN_DOMAIN}
    - REACT_APP_UI_CLUEDIN_FEATURES=follow;savedSearches;users;data-governance;developer;settings;integrations;extended-sar;cluedinClean;annotation;datasource
    - REACT_APP_UI_CLUEDIN_CLEAN_URL=http://${CLUEDIN_DOMAIN}:${CLUEDIN_OPENREFINE_LOCALPORT:-3333}/
    - REACT_APP_UI_GQL_URL=http://${CLUEDIN_DOMAIN}:${CLUEDIN_GQL_LOCALPORT:-8888}/
    - REACT_APP_UI_COOKIE_DOMAIN_NAME=${CLUEDIN_DOMAIN}
    - REACT_APP_UI_ENV=production
    - REACT_APP_UI_MAIN_DOMAIN=${CLUEDIN_DOMAIN}
    - REACT_APP_UI_PROTOCOL=http://
    depends_on:
    - server

  gql:
    image: cluedin/cluedin-ui-gql:${CLUEDIN_DOCKER_TAG}
    environment:
        - "AUTH_API=http://${CLUEDIN_SERVER_HOST:-server}:9001/"
        - "WEB_API=http://${CLUEDIN_SERVER_HOST:-server}:9000/"
        - "MICRO_CLEAN_URL=http://${CLUEDIN_CLEAN_HOST:-clean}:${CLUEDIN_CLEAN_PORT:-8888}"
        - "MICRO_ANNOTATION_URL=http://${CLUEDIN_ANNOTATION_HOST:-annotation}:${CLUEDIN_ANNOTATION_PORT:-8888}"
        - "MICRO_DATASOURCE_URL=http://${CLUEDIN_DATASOURCE_HOST:-datasource}:${CLUEDIN_DATASOURCE_PORT:-8888}"
        - "APP_API_URL=http://${CLUEDIN_WEBAPI_HOST:-webapi}:9008/"
        - "PUBLIC_API=http://${CLUEDIN_SERVER_HOST:-server}:9007/"
        - "WEBHOOKS_URL=http://${CLUEDIN_SERVER_HOST:-server}:9006/"
    ports:
    - "${CLUEDIN_GQL_LOCALPORT:-8888}:8888"
    depends_on:
    - annotation
    - clean
    - datasource
    - webapi