version: '3.7'
services:
    smtp4dev:
        image: rnwood/smtp4dev:latest
        ports:
            - "${CLUEDIN_SMTP_HTTP_LOCALPORT:-25258}:80"
            - "${CLUEDIN_SMTP_EMAIL_LOCALPORT:-2525}:25"
        volumes:
            - type: bind
              source: ./data/smtp4dev/data
              target: /smtp4dev
    neo4j:
        image: cluedin/neo4j:${CLUEDIN_NEO4J_TAG}
        environment:
            - NEO4J_AUTH=none
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
        ports:
            - "${CLUEDIN_NEO4J_HTTP_LOCALPORT:-7474}:7474"
            - "${CLUEDIN_NEO4J_BOLT_LOCALPORT:-7687}:7687"
        volumes:
            - type: bind
              source: ./data/neo4j/data
              target: /data
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
        environment:
            - discovery.type=single-node
        ports:
            - "${CLUEDIN_ELASTIC_HTTP_LOCALPORT:-9200}:9200"
            - "${CLUEDIN_ELASTIC_DATA_LOCALPORT:-9300}:9300"
        volumes:
            - type: bind
              source: ./data/elasticsearch/data
              target: /usr/share/elasticsearch/data
    rabbitmq:
        image: rabbitmq:3.9.7-management-alpine
        ports:
            - "${CLUEDIN_RABBITMQ_DATA_LOCALPORT:-5672}:5672"
            - "${CLUEDIN_RABBITMQ_HTTP_LOCALPORT:-15672}:15672"
            - "${CLUEDIN_RABBITMQ_METRICS_LOCALPORT:-15692}:15692"
        environment:
            - RABBITMQ_DEFAULT_USER=${CLUEDIN_RABBITMQ_USERNAME:-guest}
            - RABBITMQ_DEFAULT_PASS=${CLUEDIN_RABBITMQ_PASSWORD:-guest}
        hostname: cluedin-dev
        volumes:
            - type: bind
              source: ./prometheus/rabbitmq.conf
              target: /etc/rabbitmq/conf.d/rabbitmq.conf
    redis:
        image: redis:5.0-alpine
        ports:
            - "${CLUEDIN_REDIS_LOCALPORT:-6379}:6379"
    seq:
        image: datalust/seq:latest
        environment:
            ACCEPT_EULA: 'Y'
        ports:
            - "${CLUEDIN_SEQ_UI_LOCALPORT:-3200}:80"
            - "${CLUEDIN_SEQ_DATA_LOCALPORT:-5341}:5341"
    openrefine:
        image: cluedin/openrefine:${CLUEDIN_OPENREFINE_TAG}
        ports:
            - "${CLUEDIN_OPENREFINE_LOCALPORT:-3333}:3333"
    prometheus:
        image: prom/prometheus:latest
        deploy:
            replicas: ${CLUEDIN_PROMETHEUS_SCALE_COUNT:-0}
        ports:
            - "9090:9090"
        volumes:
            - type: bind
              source: ./prometheus/prometheus.yml
              target: /etc/prometheus/prometheus.yml
        command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    grafana:
        image: grafana/grafana:latest
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_SECURITY_ALLOW_EMBEDDING=true
            - GF_USERS_DEFAULT_THEME=light
            - GF_USERS_ALLOW_SIGN_UP=false
            - GF_USERS_ALLOW_ORG_CREATE=false
            - GF_AUTH_DISABLE_SIGNOUT_MENU=true
        ports:
            - "3030:3000"
        volumes:
            - type: bind
              source: ./grafana/dashboards.yml
              target: /etc/grafana/provisioning/dashboards/dashboards.yml
            - type: bind
              source: ./grafana/datasource.yml
              target: /etc/grafana/provisioning/datasources/datasource.yml
            - type: bind
              source: ./grafana/datasource-dashboard.json
              target: /var/lib/grafana/dashboards/datasource-dashboard.json
            - type: bind
              source: ./grafana/streams-dashboard.json
              target: /var/lib/grafana/dashboards/streams-dashboard.json
            - type: bind
              source: ./grafana/rabbitmq-dashboard.json
              target: /var/lib/grafana/dashboards/rabbitmq-dashboard.json
            - type: bind
              source: ./grafana/cadvisor.json
              target: /var/lib/grafana/dashboards/cadvisor.json
            - type: bind
              source: ./grafana/cadvisor-global.json
              target: /var/lib/grafana/dashboards/cadvisor-global.json
    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        ports:
            - "8484:8080"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        depends_on:
            - sqlserver
